use-singularity: True
singularity-args: >-
  -B $(pwd)/R:/home/R
  -B $(pwd)/scripts:/home/scripts
  -B $(pwd)/inst:/home/inst
  -B ${HOME}:${HOME}
  ${WORK:+-B ${WORK}:${WORK}}
  -B ${DATA_DIR}:${DATA_DIR}
  -B ${RESULTS_DIR}:${RESULTS_DIR}
  -B ${PIPELINE_DATA_DIR}:${PIPELINE_DATA_DIR}
  -B ${QTL_DATA_DIR}:${QTL_DATA_DIR}
  -B /tmp:/tmp
  --env-file .env
  --pwd /home/scripts/

jobs: 1
default-resources:
  - mem_mb=16000
  - threads=8
local-cores: 1
latency-wait: 10
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
