devtools::install_github(c("Osmahmoud/SlopeHunter",
                           "phenoscanner/phenoscanner",
                           "MRCIEU/ieugwasr",
                           "MRCIEU/TwoSampleMR",
                           "MRCIEU/gwasvcf",
													 "nicksunderland/genepi.utils",
                           "suchestoncampbelllab/gwasurvivr",
                           "yixuan/prettydoc")
)
